wowser

diff --git a/dotfiles/zsh.functions.d/functions b/dotfiles/zsh.functions.d/functions
--- a/dotfiles/zsh.functions.d/functions
+++ b/dotfiles/zsh.functions.d/functions
@@ -22,43 +22,43 @@ extract() { # Handy Extract Program.
     case "$1" in
       *.7z)
         7z x "$1"
-      ;;
+        ;;
       *.rar)
         unrar x "$1"
-      ;;
+        ;;
       *.tar.bz2)
         tar xvjf "$1"
-      ;;
+        ;;
       *.tar.gz)
         tar xvzf "$1"
-      ;;
+        ;;
       *.tar)
         tar xvf "$1"
-      ;;
+        ;;
       *.tbz2)
         tar xvjf "$1"
-      ;;
+        ;;
       *.bz2)
         bunzip2 "$1"
-      ;;
+        ;;
       *.gz)
         gunzip "$1"
-      ;;
+        ;;
       *.tgz)
         tar xvzf "$1"
-      ;;
+        ;;
       *.xz)
         tar xvf "$1"
-      ;;
+        ;;
       *.zip)
         unzip "$1"
-      ;;
+        ;;
       *.Z)
         uncompress "$1"
-      ;;
+        ;;
       *)
         echo "'$1' cannot be extracted via >extract<"
-      ;;
+        ;;
     esac
   else
     echo "'$1' is not a valid file"
@@ -108,165 +108,65 @@ settermtype() { # Set terminal type
 
 # get IP {{{
 get_configured_ip() {
-    if ! type ifconfig &> /dev/null
-    then
-        return
-    fi
+  if ! type ifconfig &> /dev/null
+  then
+    return
+  fi
 
-    if [[ -n "$OVERRIDE_NIC" ]]
+  if [[ -n "$OVERRIDE_NIC" ]]
+  then
+    NIC="$OVERRIDE_NIC"
+  elif [[ -n "$OVERRIDE_INTERFACE" ]]
+  then
+    NIC="$OVERRIDE_INTERFACE"
+  else
+    if uname -a | \grep grsec &> /dev/null
     then
-        NIC="$OVERRIDE_NIC"
-    elif [[ -n "$OVERRIDE_INTERFACE" ]]
+      return
+    elif uname -a | \grep --ignore-case cygwin &> /dev/null
     then
-        NIC="$OVERRIDE_INTERFACE"
-    else
-        if uname -a | \grep grsec &> /dev/null
+      HOST_IP="$(ifconfig | \grep --ignore-case "ipv4 address"| head -1 | cut -d: -f2 | cut -d"(" -f1 | cut -d" " -f2)"
+    elif uname -a | \grep --ignore-case darwin &> /dev/null
+    then
+      IFACE_PREFIX="en"
+      for i in {0..9}
+      do
+        if ifconfig "$IFACE_PREFIX""$i" 2> /dev/null | \grep --word-regexp --quiet active && ifconfig "$IFACE_PREFIX""$i" 2> /dev/null | \grep --word-regexp --quiet inet
         then
-            return
-        elif uname -a | \grep --ignore-case cygwin &> /dev/null
-        then
-            HOST_IP="$(ifconfig | \grep --ignore-case "ipv4 address"| head -1 | cut -d: -f2 | cut -d"(" -f1 | cut -d" " -f2)"
-        elif uname -a | \grep --ignore-case darwin &> /dev/null
-        then
-          IFACE_PREFIX="en"
-          for i in {0..9}
-          do
-              if ifconfig "$IFACE_PREFIX""$i" 2> /dev/null | \grep --word-regexp --quiet active && ifconfig "$IFACE_PREFIX""$i" 2> /dev/null | \grep --word-regexp --quiet inet
-              then
-                HOST_IP="$(ifconfig "$IFACE_PREFIX""$i" | \grep --word-regexp inet | tail -1 | awk '{print $2}')"
+          HOST_IP="$(ifconfig "$IFACE_PREFIX""$i" | \grep --word-regexp inet | tail -1 | awk '{print $2}')"
 
-                break
-              fi
-          done
-        elif uname -a | \grep --ignore-case linux &> /dev/null
-        then
-            NIC="$(ip addr | \grep --invert-match NO-CARRIER | \grep -E "\<.*,?UP,?.*\>" | \grep --invert-match lo | head -1 | cut -d" " -f2 | cut -d":" -f1)"
-        else
-            echo "Unsupported OS while determining host IP"
+          break
         fi
-    fi
-    INTERFACE="$NIC"
-    export INTERFACE
-
-    if [[ -n "${NIC}" ]]
+      done
+    elif uname -a | \grep --ignore-case linux &> /dev/null
     then
-        HOST_IP="$(ifconfig "${NIC}" | \grep -w inet | \grep -v 127.0 | head -n 1 | awk '{print $2}')"
-    fi
-
-    if [[ -z "$HOST_IP" ]]
-    then
-        return
+      NIC="$(ip addr | \grep --invert-match NO-CARRIER | \grep -E "\<.*,?UP,?.*\>" | \grep --invert-match lo | head -1 | cut -d" " -f2 | cut -d":" -f1)"
     else
-        if [[ "$(echo "$HOST_IP" | \grep -c addr)" -eq 1 ]]
-        then
-            CONFIGURED_IP="$(echo "$HOST_IP" | cut -d : -f 2)"
-        else
-            CONFIGURED_IP="$HOST_IP"
-        fi
-
-        export HOST_IP
-        export CONFIGURED_IP
+      echo "Unsupported OS while determining host IP"
     fi
-}
-# }}}
+  fi
+  INTERFACE="$NIC"
+  export INTERFACE
 
-# set hostname variables {{{
-set_local_internal_host_variables() {
-    INTERNALIP="NONE"
-    INTERNALHOST="$(hostname -f)"
-    INTERNALDOMAIN="$(hostname -f)"
-    INTERNALHOSTNAME="$(hostname -s)"
-}
+  if [[ -n "${NIC}" ]]
+  then
+    HOST_IP="$(ifconfig "${NIC}" | \grep -w inet | \grep -v 127.0 | head -n 1 | awk '{print $2}')"
+  fi
 
-set_local_external_host_variables() {
-    EXTERNALIP="NONE"
-    EXTERNALHOST="$(hostname -f)"
-    EXTERNALDOMAIN="$(hostname -f)"
-    EXTERNALHOSTNAME="$(hostname -s)"
-}
-
-set_local_host_variables() {
-    set_local_internal_host_variables
-    set_local_external_host_variables
-}
-
-set_host_variables() {
-    get_configured_ip
-
-    if [[ -z "$CONFIGURED_IP" ]]
+  if [[ -z "$HOST_IP" ]]
+  then
+    return
+  else
+    if [[ "$(echo "$HOST_IP" | \grep -c addr)" -eq 1 ]]
     then
-        set_local_host_variables
+      CONFIGURED_IP="$(echo "$HOST_IP" | cut -d : -f 2)"
     else
-        if [[ -z "$DISABLE_PUBLIC_IP_CHECK" ]]
-        then
-            if which curl &> /dev/null
-            then
-                PUBLIC_IP="$(curl -4 --silent --fail --max-time 2 https://www.waf.hk/ip)"
-            else
-                PUBLIC_IP="$(wget -4 --quiet --output-document=- --timeout=2 https://www.waf.hk/ip)"
-            fi
-
-            LOCAL_NAMESERVER="$(\grep nameserver /etc/resolv.conf | head -1 | awk '{print $NF}')"
-            if [[ "$PUBLIC_IP" =~ ^[0-9].+ ]]
-            then
-                EXTERNALIP="$PUBLIC_IP"
-                EXTERNALHOST="$(/usr/bin/dig +short -x "$EXTERNALIP" @"$LOCAL_NAMESERVER" | head -1 | sed 's/\.$//')"
-                EXTERNALHOSTNAME="$(echo "$EXTERNALHOST" | cut -d"." -f1)"
-                EXTERNALDOMAIN="$(echo "$EXTERNALHOST" | cut -d"." -f2-)"
-
-                if [[ -z "$DISABLE_PRIVATE_IP_CHECK" ]]
-                then
-                    INTERNALIP="$CONFIGURED_IP"
-                    export INTERNALIP
-                    if [[ "$EXTERNALIP" == "$INTERNALIP" ]]
-                    then
-                        INTERNALHOST="$EXTERNALHOST"
-                        INTERNALHOSTNAME="$EXTERNALHOSTNAME"
-                        INTERNALDOMAIN="$EXTERNALDOMAIN"
-                    else
-                        INTERNALHOST="$(/usr/bin/dig +short -x "$INTERNALIP" @"$LOCAL_NAMESERVER" | head -1 | sed "s/\.$//")"
-                        INTERNALHOSTNAME="$(echo "$INTERNALHOST" | cut -d"." -f1)"
-                        INTERNALDOMAIN="$(echo "$INTERNALHOST" | cut -d"." -f2-)"
-                    fi
-                else
-                    set_local_internal_host_variables
-                fi
-            fi
-        else
-            set_local_external_host_variables
-        fi
+      CONFIGURED_IP="$HOST_IP"
     fi
 
-    HOST="$1"
-    if [[ "$HOST" == "" ]]
-    then
-        if [[ x"$EXTERNALHOST" != x"" ]]
-        then
-            REALHOST="$EXTERNALHOST"
-        elif [[ x"$INTERNALHOST" != x"" ]]
-        then
-            REALHOST="$INTERNALHOST"
-        else
-            REALHOST="$(hostname -f)"
-        fi
-    else
-        REALHOST="$HOST"
-    fi
-
-    HOSTNAME="$(hostname)"
-    FULL_HOSTNAME="$(hostname -f)"
-    export HOSTNAME
-    export FULL_HOSTNAME
-    export INTERNALIP
-    export INTERNALHOST
-    export INTERNALDOMAIN
-    export INTERNALHOSTNAME
-    export EXTERNALIP
-    export EXTERNALHOST
-    export EXTERNALDOMAIN
-    export EXTERNALHOSTNAME
-    export REALHOST
-    export PUBLIC_IP
+    export HOST_IP
+    export CONFIGURED_IP
+  fi
 }
 # }}}
 
@@ -322,49 +222,49 @@ open_command() {
       ;;
     linux*)
       [[ "$(uname -r)" != *icrosoft* ]] && open_cmd='nohup xdg-open' || {
-                open_cmd="cmd.exe /c start ''"
-                [[ -e "$1" ]] && ( 1="$(wslpath -w "${1:a}")" || return 1 )
-              }
-              ;;
-    msys*)
-      open_cmd='start ""'
-      ;;
-    *)
-      echo "Platform $OSTYPE not supported"
-      return 1
-      ;;
-  esac
+        open_cmd="cmd.exe /c start ''"
+              [[ -e "$1" ]] && ( 1="$(wslpath -w "${1:a}")" || return 1 )
+            }
+            ;;
+          msys*)
+            open_cmd='start ""'
+            ;;
+          *)
+            echo "Platform $OSTYPE not supported"
+            return 1
+            ;;
+        esac
 
-  ${=open_cmd} "$@" &>/dev/null
-}
-# }}}
+        ${=open_cmd} "$@" &>/dev/null
+      }
+      # }}}
 
 # exponential backoff {{{
 exponential_backoff() {
-    # Exponential backoff: retries a command upon failure, scaling up the delay between retries.
-    # Example: "expbackoff my_command --with --some --args --maybe"
-    local MAX_RETRIES=${EXPBACKOFF_MAX_RETRIES:-19} # Max number of retries
-    local BASE=${EXPBACKOFF_BASE:-1} # Base value for backoff calculation
-    local MAX=${EXPBACKOFF_MAX:-9999999} # Max value for backoff calculation
-    local FAILURES=0
+  # Exponential backoff: retries a command upon failure, scaling up the delay between retries.
+  # Example: "expbackoff my_command --with --some --args --maybe"
+  local MAX_RETRIES=${EXPBACKOFF_MAX_RETRIES:-19} # Max number of retries
+  local BASE=${EXPBACKOFF_BASE:-1} # Base value for backoff calculation
+  local MAX=${EXPBACKOFF_MAX:-9999999} # Max value for backoff calculation
+  local FAILURES=0
 
-    while ! "$@"; do
-        FAILURES=$(( $FAILURES + 1 ))
-        if (( $FAILURES > $MAX_RETRIES )); then
-            echo "$@" >&2
-            echo " * Failed, max retries exceeded" >&2
-            return 1
-        else
-            local SECONDS=$(( $BASE * 2 ** ($FAILURES - 1) ))
-            if (( $SECONDS > $MAX )); then
-                SECONDS=$MAX
-            fi
-            echo "$@" >&2
-            echo_color red " * $FAILURES failure(s), retrying in $SECONDS second(s)" >&2
-            sleep $SECONDS
-            echo
-        fi
-    done
+  while ! "$@"; do
+    FAILURES=$(( $FAILURES + 1 ))
+    if (( $FAILURES > $MAX_RETRIES )); then
+      echo "$@" >&2
+      echo " * Failed, max retries exceeded" >&2
+      return 1
+    else
+      local SECONDS=$(( $BASE * 2 ** ($FAILURES - 1) ))
+      if (( $SECONDS > $MAX )); then
+        SECONDS=$MAX
+      fi
+      echo "$@" >&2
+      echo_color red " * $FAILURES failure(s), retrying in $SECONDS second(s)" >&2
+      sleep $SECONDS
+      echo
+    fi
+  done
 }
 expbackoff=exponential_backoff
 # }}}
